name: 'Auto Release Draft'
description: 'Draft a Github release with the changes introduced by newly created tag'
author: 'Dayana Myk'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.


# Define your outputs here.
outputs:
  release-url:
    description: 'The URL of the Github release that was crafted'

runs:
  using: node20
  main: dist/index.js
