name: 'Auto Release Draft'
description: 'Draft a Github release with the changes introduced by newly created tag'
author: 'Dayana Myk'

# Define your inputs here.
inputs:
 repo-token:
  description: 'The GITHUB_TOKEN used to authenticate to the current '
  required: true

# Define your outputs here.
outputs:
  release-url:
    description: 'The URL of the Github release that was crafted'

runs:
  using: node20
  main: dist/index.js
